### ISSUE TITLE
Compiling for MC 1.12

### ISSUE THREAD

**Issue by Leeo97one** [GameModsBR/VoiceChat#11]
Can we compile the mod for Minecraft 1.12 right now?

**Comment by utkabobr** [comment]
Yes, just run gradlew build

**Comment by Leeo97one** [comment]
I already try many times but: https://pastebin.com/aJ6XbD18

**Comment by utkabobr** [comment]
It seems that you are using outdated build.gradle

**Comment by utkabobr** [comment]
And that I forgot to upload fresh build.gradle...
I'll do that now

**Comment by Leeo97one** [comment]
And so, what's the solution? Sorry I never compiled a Minecraft mod before x)

**Comment by Leeo97one** [comment]
OK thanks ^_^

**Comment by utkabobr** [comment]
For now, before @Gliby or @joserobjr merge pull request, you can use build.gradle from here: https://github.com/utkabobr/VoiceChat/blob/master/build.gradle

**Comment by Leeo97one** [comment]
Nice!
```
BUILD SUCCESSFUL

Total time: 2 mins 7.853 secs
```
I'll test the mod a bit later.
